const en = {
  appName: 'Clare',
  logoName: 'Clare & Me',
  getStarted: 'Get Started',
  skip: 'Skip',
  done: 'Done',
  cancel: 'Cancel',
  next: 'Next',
  back: 'Back',
  ok: 'OK',
  okay: 'Okay',
  yes: 'Yes',
  no: 'No',
  send: 'Send',
  confirm: 'Confirm',
  delete: 'Delete',
  allDataRequired: 'All Data Required',
  emailAndPassRequired: 'Please enter your email and password',
  submit: 'Submit',
  close: 'Close',
  add: 'Add',
  or: 'OR',
  edit: 'Edit',
  save: 'Save',
  continue: 'Continue',
  noConnection: 'No connection',
  checkInternet: 'Check your internet connection',
  refresh: 'Refresh',
  goBack: 'Go back',
  letsGo: 'Let’s go',
  select: 'Select',
  hey: 'Hey',
  and: 'and',
  yay: 'Yay',

  onBoarding: {
    title1: 'What is Lorem Ipsum?',
    title2: 'Why do we use it?',
    title3: 'Where does it come from?',
    description1:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries. ",
    description2:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    description3:
      'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.',
  },

  home: 'Home',
  news: 'News',
  search: 'Search',
  settings: 'Settings',
  themes: {
    title: 'Themes',
    light: 'Light',
    dark: 'Dark',
  },
  languages: {
    title: 'Languages',
    en: 'English',
    ar: 'Arabic',
  },
  emptySearch: 'No result found',
  tryAnotherWord: 'Please try another search word',
  newDetails: 'New Details',
  description: 'Description',
  content: 'Content',
  share: 'Share',
};

export default en;
